apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ofk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-utdanning-larling-adapter
  app.kubernetes.io/instance: fint-utdanning-larling-adapter_ofk_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: adapter
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: ofk.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-utdanning-larling-adapter_ofk_no"
      - op: replace
        path: "/spec/orgId"
        value: "ofk.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "31"
      - op: replace
        path: "/spec/env/2/value"
        value: "https://api.felleskomponent.no"
      - op: replace
        path: "/spec/env/3/value"
        value: "ofk.no"
    target:
      kind: Application
      name: fint-utdanning-larling-adapter

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-utdanning-larling-adapter_ofk_no"
      - op: replace
        path: "/spec/orgId"
        value: "ofk.no"
    target:
      kind: FintAdapter
      name: utdanning-larling-adapter